name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.9 pip freeze > requirements.txt

  build:
    needs: setup
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged  # Required for Docker-in-Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t my-python-soul.py

      - name: Run setup script in Docker
        run: |
          docker run -p 4000:80 my-python-soul.py

      - name: Compile C++ and run Python script
        run: |
          docker run --rm my-python-app bash -c "g++ -o raja loda.cpp -std=c++11 -pthread && chmod +x * && echo 'Running the script...' && python3 soul.py"

      - name: Restart pipeline (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
          echo "Restarting the pipeline..."
          curl -X POST -F token=${{ secrets.GITHUB_TOKEN }} -F ref=main https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches

  new_function:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute New Function
        run: |
          echo "Executing new function..."
          # Add your specific commands or scripts here.

  new_t:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute New Task
        run: |
          echo "Executing new task in the new_t job..."
          # Add your specific commands or scripts for the new task here.
          
