name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment
        run: |
          echo "Setting up environment"
          sudo apt-get update && sudo apt-get install -y gcc
          echo "Environment setup complete."

  run_script:
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install GCC (if needed)
        run: |
          sudo apt-get update && sudo apt-get install -y gcc
      
      - name: Compile C++ file
        run: |
          echo "Compiling Cpp file into binary..."
          g++ -o soul loda.cpp -std=c++11 -pthread
      
      - name: Install Python dependencies
        run: |
          pip install telebot pymongo aiohttp
      
      - name: Make files executable
        run: chmod +x *
      
      - name: Run the Python script
        run: python3 soul.py

  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: run_script
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile  # Specify your Dockerfile path if different
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest

  restart_pipeline:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Sleep before restarting
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
      
      - name: Restart the pipeline
        run: |
          echo "Restarting the pipeline..."
          curl -X POST -F token=${{ secrets.CI_JOB_TOKEN }} -F ref=main https://gitlab.com/api/v4/projects/${{ secrets.CI_PROJECT_ID }}/trigger/pipeline
