name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This is only for the job runner, not for building
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Run setup script in Docker
        run: |
          docker run --rm my-python-app bash -c "echo 'Setting up environment...'; echo 'Environment setup complete.'"

      - name: Compile C++ and run Python script
        run: |
          docker run --rm my-python-app bash -c "g++ -o raja loda.cpp -std=c++11 -pthread && chmod +x * && echo 'Running the script...' && python3 soul.py"

      - name: Restart pipeline (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
          echo "Restarting the pipeline..."
          curl -X POST -F token=${{ secrets.GITHUB_TOKEN }} -F ref=main https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches
