name: Python and C++ Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    container:
      image: python:3.9

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup the environment
      - name: Setup environment
        run: |
          echo "Setting up environment"
          sudo apt-get update
          sudo apt-get install -y gcc
          sudo apt-get install -y build-essential
          echo "Environment setup complete."

      # Compile C++ file into binary
      - name: Compile C++ program
        run: |
          echo "Compiling C++ program"
          g++ -o raja raja.cpp -std=c++11 -pthread
        

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Python script
      - name: Run Python script
        run: |
          echo "Running Python script"
          python soul.py
