name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment
        run: |
          echo "Setting up environment"
          sudo apt-get update && sudo apt-get install -y gcc
          echo "Environment setup complete."

  run_script:
    runs-on: python:3.9
    needs: setup_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile C++ file
        run: |
          echo "Compiling Cpp file into binary..."
          g++ -o soul loda.cpp -std=c++11 -pthread
          pip install telebot pymongo aiohttp
          chmod +x *
          echo "Running the script..."
          python3 soul.py

  restart_pipeline:
    runs-on: python:3.9
    needs: run_script
    steps:
      - name: Sleep and restart pipeline
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
          echo "Restarting the pipeline..."
          curl -X POST -F token=${{ secrets.GITHUB_TOKEN }} -F ref=main https://api.github.com/repos/${{ github.repository }}/actions/workflows/your_workflow_id/dispatches
