name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.9 pip install -r requirements.txt

  docker-build:
    needs: dependencies
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

  cpp-compile:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Compile C++
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_NAME }} bash -c "g++ -o raja loda.cpp -std=c++11 -pthread && chmod +x *"

  python-script:
    needs: d```yaml
 python-script:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Run Python script
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_NAME }} bash -c "echo 'Running the script...' && python3 soul.py"

  restart-pipeline:
    needs: docker-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Sleep and restart pipeline
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
          echo "Restarting the pipeline..."
          curl -X POST -F token=${{ secrets.GITHUB_TOKEN }} -F ref=main https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches

  execute-function:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Execute new function
        run: |
          echo "Executing new function..."
          # Add your specific commands or scripts here.

  execute-task:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Execute new task
        run: |
          echo "Executing new task in the execute-task job..."
          # Add your specific commands or scripts for the new task here.
