name: Python and C++ Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: macos-latest  # Use an Ubuntu runner with Docker pre-installed

    steps:
      # Step to check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to set up Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you want to use

      # Step to install system dependencies
      - name: Install system dependencies
        run: |
          echo "Installing system dependencies"
          sudo apt-get update && sudo apt-get install -y gcc g++  # Install C++ compiler
          echo "System dependencies installed."

      # Step to compile the C++ program into a binary
      - name: Compile C++ program
        run: |
          echo "Compiling C++ program"
          g++ -o raja loda.cpp -std=c++11 -pthread  # Replace with your actual C++ file name
          echo "C++ program compiled successfully."
                 # Execute the compiled program

      # Step to install Python dependencies
      - name: Install Python dependencies
        run: |
          echo "Installing Python dependencies"
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step to run the Python script
      - name: Run Python script
        run: |
          echo "Running Python script"
          python soul.py  # Replace with your actual Python script name
