name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version
      
      - name: Install dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.9 pip install -r requirements.txt

  build:
    needs: setup
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged  # Required for Docker-in-Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Avoid redundancy if using a single workspace
      
      - name: Build Docker image
        run: |
          docker build -t my-python-cpp-app .

      - name: Run setup script in Docker
        run: |
          docker run -d -p 4000:80 my-python-cpp-app

      - name: Compile C++ in to banary 
        run: |
          docker run --rm my-python-cpp-app bash -c gcc -o raja loda.cpp -std=c++11 -pthread

      - name: Restart pipeline (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
          echo "Restarting the pipeline..."
          curl -X POST \
            -F token=${{ secrets.GITHUB_TOKEN }} \
            -F ref=main \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches

  new_function:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute New Function
        run: |
          python soul.py
          echo "Executing new function..."
          # Add your specific commands or scripts here.

  new_t:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute New Task
        run: |
          echo "Executing new task in the new_t job..."
          # Add your specific commands or scripts for the new task here.
