name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-20.04
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          set -e  # Exit on error
           pip install telebot pymongo flask aiogram pyTelegramBotAPI python-telegram-bot # Ensure telebot is included here

      - name: Run setup script
        run: |
          echo 'Setting up environment...'
          echo 'Environment setup complete.'

  build_and_run:
    runs-on: ubuntu-20.04
    needs: setup_environment
    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Compile C++ and run Python script
        run: |
          set -e  # Exit on error
          g++ -o raja loda.cpp -std=c++11 -pthread || { echo 'Compilation failed'; exit 1; }
          chmod +x * && python3 soul.py

      - name: Restart pipeline (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Sleeping for 1 hour before restarting..."
          sleep 3600
          echo "Restarting the pipeline..."
          curl -X POST \
            -F token=${{ secrets.GITHUB_TOKEN }} \
            -F ref=main \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches || { echo 'Failed to restart pipeline'; exit 1; }
